<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Abstracts' => '',
    'Abstracts ID' => '',
    'Abstracts Users' => '',
    'Are you sure you want to delete this item?' => '',
    'Autor' => '',
    'Contacto' => '',
    'Contraseña' => '',
    'Correo Electrónico' => '',
    'Create' => '',
    'Create Abstracts' => '',
    'Create Abstracts Users' => '',
    'Create Panels' => '',
    'Create Users' => '',
    'Crédito Académico' => '',
    'Delete' => '',
    'Enviar' => '',
    'Enviar Resumen' => '',
    'Envios' => '',
    'Fechas' => '',
    'Guardar' => '',
    'ID' => '',
    'Mesa Tematica' => '',
    'Mesas' => '',
    'Name' => '',
    'Nombre Completo' => '',
    'Panels' => '',
    'Registrarse' => '',
    'Reset' => '',
    'Resumen' => '',
    'Search' => '',
    'Sobre' => '',
    'Update' => '',
    'Update {modelClass}: ' => '',
    'Users' => '',
    'Users ID' => '',

    // Section Theme
    'Tema' => '',
    'Theme_Title_1' => 'Estado, sociedad',
    'Theme_Title_2' => 'y mercado',
    'Theme_Subtitle' => 'nuevas perspectivas para el desarrollo',
    'Theme_Text_1' => 'Las instituciones neoliberales y la estrategia de promoción del desarrollo económico con protagonimdo del mercado, vaciamiento del papel del estado y escasa política social parecía que entraba en jaque con la crisis financiera internacional y la gran depresión. Ya a finales de los años 1990 se observaba una cierta tendencia de cambio en la estrategia de desarrollo de los países iberoamericanos, dado la incapacidad de ese modelo neoliberal para promover crecimiento económico con distribución de la renta. Esa tendencia también se ha manifestado en el mundo académico, con una constante búsqueda de revisión del paradigma dominante y la recuperación de una perspectiva teórica heterodoxa y multidisciplinar. Sin embargo, después de seis años desde la deflagración de la crisis, persisten los interrogantes políticos y teóricos sobre las nuevas estrategias para el desarrollo de la región. Los países emergentes están en un momento decisivo de definición de esas estrategias de desarrollo sostenido, no obstante, el debate teórico académico, a pesar de haber avanzado mucho en los últimos años, todavía no es capaz de ofrecer una respuesta mínimamente consensuada sobre varios aspectos chaves del desarrollo.',
    'Theme_Text_2' => 'En este contexto surgen varias cuestiones fundamentales para el estudio del desarrollo socioeconómico de la región y que serán objeto de debate en la II RISE. Se destaca, por un laco, el papel del Estado, i.e., la construcción de una agenda que defina las características de la actuación del Estado en el desarrollo, especialmente en el contexto de la globalización, con autonomía para tomar decisiones, articular el mercado y la política industrial, con un papel proactivo en la promoción del desarrollo, con una política fiscal y crediticia contra-cíclica, de estimulo a la modernización de las infraestructuras, del fortalecimiento de la industria y mejoras en la calidad de las políticas sociales. Se admite, además, la existencia de varias formas de capitalismo, con distintas combinaciones institucionales, destacando la importancia del Estado en la coordinación de políticas promotoras del crecimiento y de la productividad.',
    'Theme_Text_3' => 'En fin, las demandas socioeconómicas de los países iberoamericanos colocan en la agenda de discusión cuestiones relevantes sobre las estrategias y obstáculos del desarrollo sostenido a largo plazo, y que deben analizarse desde el punto de vista teórico, político y multidisciplinar. En este sentido, la II RISE pretende debatir cuestiones relacionadas con los siguientes temas: el papel del estado en la socio-economía; el desarrollo en los países iberoamericanos: desafíos y perspectivas; democracia, ciudadanía y movimientos sociales: macroeconomía, sistemas financieros y regulación; demografía y desarrollo regional; empleo, calidad de vida y políticas sociales; desarrollo sostenido y medio-ambiente; desindustrialización y patrones de comercio; y relaciones internacionales e integración regional.',

];
