<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	'Abstracts' => '',
	'Abstracts ID' => '',
	'Abstracts Users' => '',
	'Are you sure you want to delete this item?' => '',
	'Autor' => 'Autor',
	'Contacto' => 'Contato',
	'Contraseña' => '',
	'Correo Electrónico' => 'E-mail',
	'Create' => 'Criar',
	'Create Abstracts' => '',
	'Create Abstracts Users' => '',
	'Create Panels' => '',
	'Create Users' => '',
	'Crédito Académico' => '',
	'Delete' => 'Apagar',
	'Enviar' => '',
	'Enviar Resumen' => '',
	'Envios' => '',
	'Fechas' => 'Prazo',
	'Guardar' => 'Salvar',
	'ID' => '',
	'Mesa Tematica' => '',
	'Mesas' => '',
	'Name' => '',
	'Nombre Completo' => '',
	'Panels' => '',
	'Registrarse' => 'Registrar',
	'Reset' => '',
	'Resumen' => '',
	'Search' => 'Busca',
	'Sobre' => '',
	'Tema' => '',
	'Update' => 'Atualizar',
	'Update {modelClass}: ' => '',
	'Users' => '',
	'Users ID' => '',
];
